### ISSUE TITLE
Please maintain a CHANGELOG

### ISSUE THREAD

**Issue by MoOx** [ByteMuse/cssnextify#1]
This would be nice :)
If you want we can host this package under cssnext org

**Comment by ByteMuse** [comment]
Thank you for the offer, that would be great :). Did you mean description in tag or CHANGELOG file?

**Comment by MoOx** [comment]
I personally generate github release from a CHANGELOG file.
I think a CHANGELOG (included in npm release) are a good practice so people can read it from node_modules :)

**Comment by MoOx** [comment]
I use this
https://github.com/MoOx/setup/blob/master/functions/npmpublish
(which at the end, use this https://github.com/MoOx/setup/blob/master/bin/npmrelease)

**Comment by ByteMuse** [comment]
Done. Thanks for the tools by the way!

**Comment by MoOx** [comment]
I invited you to cssnext org, feel free to move your repo over there :)
